### ISSUE TITLE
Feature: User can search for rentals near/in a specific location.

### ISSUE THREAD

**Issue by Mitchelllund** [Mitchelllund/ajax-project#1]
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a skeleton for the HTML.
- [ ] Create the heading and add the app name.
- [ ] Add a HTML `form` element that will include all of the pages `input` elements. 
- [ ] ... more to add
